### ISSUE TITLE
The effective parameters on the number of data tiles 

### ISSUE THREAD

**Issue by narges-tk** [drprojects/superpoint_transformer#161]
Hi!
Based on my experience, I see that for my different datasets, one point cloud file is tiled to 9 files during pre-processing step. I played with some hyper parameters in the config>datamodule>semantic but still the number of tiles are same. May I please ask you to help me how can I change the number of tiles for each point cloud?
Thanks & best regards,
Narges

**Comment by drprojects** [comment]
Hi @narges-tk

If your question is: "_I want all my clouds to be tiled into the same amount of sub-tiles but I would rather have less than 9 tiles, how can I do so_". Then the answer is (as already explained in multiple places throughout the docs, codebase, issues...):

- `pc_tiling: x` will split each cloud into $2^x$ tiles, based on their principal components
- `xy_tiling: x` will split each cloud into $x^2$ tiles, based on a regular XY grid

If your question is: "_I have clouds of diverse sizes, can I divide my clouds into different number of sub-tiles depending on the size of the input clouds_". Then the answer is our 2 tiling mechanisms do not work that way at the moment. If you look at the documentation and code docstings you will see that both tiling mechanisms `SampleXYTiling` and `SampleRecursiveMainXYAxisTiling` are always producing the same number of sub-tiles per cloud, regardless of the size of the input point cloud they receive. This is because we assume datasets are divided into clouds of roughly similar sizes. So, if you want to have different numbers of sub-tiles per input cloud, you will need to implement the tiling mechanism you desire yourself. And we would gladly welcome a PR if you do so !

**Comment by narges-tk** [comment]
> Hi @narges-tk
> 
> If your question is: "_I want all my clouds to be tiled into the same amount of sub-tiles but I would rather have less than 9 tiles, how can I do so_". Then the answer is (as already explained in multiple places throughout the docs, codebase, issues...):
> 
> * `pc_tiling: x` will split each cloud into 
>     2
>     x
>    tiles, based on their principal components
> * `xy_tiling: x` will split each cloud into 
>     x
>     2
>    tiles, based on a regular XY grid
> 
> If your question is: "_I have clouds of diverse sizes, can I divide my clouds into different number of sub-tiles depending on the size of the input clouds_". Then the answer is our 2 tiling mechanisms do not work that way at the moment. If you look at the documentation and code docstings you will see that both tiling mechanisms `SampleXYTiling` and `SampleRecursiveMainXYAxisTiling` are always producing the same number of sub-tiles per cloud, regardless of the size of the input point cloud they receive. This is because we assume datasets are divided into clouds of roughly similar sizes. So, if you want to have different numbers of sub-tiles per input cloud, you will need to implement the tiling mechanism you desire yourself. And we would gladly welcome a PR if you do so !

Many thanks for your clarification :) !
