### ISSUE TITLE
RuntimeError(f"{self.__class__.__qualname__} is not attached to a `Trainer`.")

### ISSUE THREAD

**Issue by fclairec** [drprojects/superpoint_transformer#167]
Hello

Thanks very much for your comprehensive repository.

The latest commit and additions to `src/models/semantic.py` cause an error when running `python src/train.py experiment=semantic/s3dis datamodule.fold=5`

```
[2024-10-29 12:48:41,430][src.utils.utils][ERROR] -
Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/spt/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/appuser/superpoint_transformer/src/models/semantic.py", line 141, in __init__
    if self.trainer.check_val_every_n_epoch is not None:
  File "/home/appuser/miniconda3/envs/spt/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 218, in trainer
    raise RuntimeError(f"{self.__class__.__qualname__} is not attached to a `Trainer`.")
```

Without searching to understand it in detail, I figured that the access to self.trainer in __init__ with `self.trainer.check_val_every_n_epoch`  causes the error. 
Reverting to the last commit solved the issue for me.

I hope this helps 

BR
Fiona

**Comment by drprojects** [comment]
Hi @fclairec, thanks for pointing this out ! 

This is indeed an issue I recently caused by pushing some unsufficiently tested code :sweat_smile: I am working on fixing this and will push the fix as soon as possible. In the meantime, you can use commit `6cb9d93`, where none of the breaking changes were added yet.

Sorry for the inconvenience !

### If you ❤️ or simply use this project, don't forget to give the repository a ⭐, it means a lot to us !
