### ISSUE TITLE
Orientation of the ply files and affect of the segmentation

### ISSUE THREAD

**Issue by Nacriema** [drprojects/superpoint_transformer#168]
Hi, 
Thank you for sharing us the amazing work! I have a question that need to clarify. Currently I'm using the pretrained `S3DIS` weight to perform the 3D segmentation on my sample point cloud file. But the result is not good as y expected. My question is that the [x, y, z] coordinate of the point cloud like the orientation of the object the performance of the pretrained model (eg. The floor should be on the z plane or so ?). Thank you in advanced.

Here is my segmentation result with my model:
**My original point cloud**
![image](https://github.com/user-attachments/assets/75c4f9a2-20a4-499d-9f00-a2abce014820)

**The 2 images bellow just for describe the z coordinate of my point cloud**
![image](https://github.com/user-attachments/assets/85e97944-2be0-4b7f-ab1e-d1b3f06e2a7e)
![image](https://github.com/user-attachments/assets/21a840cb-bd9f-4b3e-962f-d4e4f32df7c7)

**Comment by drprojects** [comment]
Hi @Nacriema yes indeed the distribution of your data seems to differ quite a bit fro the S3DIS data, which can explain the poor generalization:
- in S3DIS, `z=0='floor'`. I agree that this is usually not the case in real life acquisition but this is how the dataset is released and the model probably relies on it. You could retrain SPT on S3DIS by adding random offsets to the Z coordinate (we do not support this, you will have to code this yourself but this should be a fairly easy `Transform` to implement)
- similarly, there is an official 'aligned' S3DIS version of the dataset which releases the individual rooms positioned in such a way that X and Y also carry important semantic meaning (X=0='door' if I remember well). While many other papers communicate their performance on S3DIS by using this data, we intentionally refused to do so as we consider it to be an unrealistic scenario. Point clouds are not necessarily acquired room by room, nor aligned in some canonical room space, defining such room division is arbitrary (e.g. open spaces), etc. So we train our models to operate on the floor level, without using the room divisions, nor room-level coordinates, or canonical orientation (see [our paper](https://arxiv.org/abs/2306.08045))
- sensor noise: S3DIS is super clean in terms of surface noise, maybe your data comes from a slightly more noisy sensor so, it is possible this affects performance. You could retrain SPT on S3DIS with more noise augmentation on the positions to see if it helps generalization. See `datamodule.pos_jitter` inthe configs for that
- acquisition artifacts: S3DIS acquisition barely has any artifacts: rooms are "almost" watertight, all have a ceiling. This is not the case of your data. So a model trained on S3DIS will likely panic if it cannot find a nice horizontal floor at `z=0` and a horizontal ceiling at the top of the z distribution. Maybe S3DIS is not the dataset you need but ScanNet is ? We do not provide pretrained weights for semantic segmentation on ScanNet but we do provide so for panoptic segmentation (for which you can get the semantic segmentation). See the `README` for that. Alternatively, you could retrain on S3DIS with a new augmentation that you implement that randomly removes big chunks (if not all) of the ceiling to better mimic your data distribution (we do not support this, you will have to implement it yourself)
- resolution: not sure which resolution you are working with but make sure this aligns with what we used in the pretrained model 
- radiometry: your colors seem quite dark to me. If you look at the RGB distribution of S3DIS data, you will see the colors are much brighter. You may want to look into aligning the color distribution of your data to S3DIS's 

Overall, it does seem your distribution is far from S3DIS and you will probably need to find solutions to better align both distributions as mentioned above. See also if ScanNet is not a better pretraining dataset for you. 

That being said, I will not be able to provide further help for tuning SPT to your needs. Due to the large number for requests we receive, we can only focus on providing support for issues related to code, models, and datasets we released ourselves. 

Hope that helps !

**Comment by Nacriema** [comment]
Wow, thank you for your great explanation!
