### ISSUE TITLE
 Focus on  specific categories accuracy only

### ISSUE THREAD

**Issue by Thomas-ia** [drprojects/superpoint_transformer#179]
### ✅ Code of conduct checklist

- [X] 🌱 I am using the **_latest version_** of the [code](https://github.com/drprojects/superpoint_transformer/tree/master).
- [X] 📙 I **_thoroughly_** went through the [README](https://github.com/drprojects/superpoint_transformer/blob/master/README.md), but could not find the feature I need there.
- [X] 📘 I **_thoroughly_** went through the tutorial [slides](media/superpoint_transformer_tutorial.pdf), [notebook](notebooks/superpoint_transformer_tutorial.ipynb), and [video](https://www.youtube.com/watch?v=2qKhpQs9gJw), but could not find the feature I need there.
- [X] 📗 I **_thoroughly_** went through the [documentation](https://github.com/drprojects/superpoint_transformer/tree/master/docs), but could not find the feature I need there.
- [X] 📜 I went through the **_docstrings_** and **_comments_** in the [source code](https://github.com/drprojects/superpoint_transformer/tree/master) parts relevant to my problem, but could not find the feature I need there.
- [X] 👩‍🔧 I searched for [**_similar issues_**](https://github.com/drprojects/superpoint_transformer/issues), but could not find the feature I need there.
- [x] ⭐ Since I am showing interest in the project, I took the time to give the [repo](https://github.com/drprojects/superpoint_transformer/tree/master) a ⭐ to show support. **Please do, it means a lot to us !**

### 🚀 The feature, motivation and pitch

I have a multi-category data set with many category annotations. I only want to focus on the accuracy of the specific category I need, and also hope to have segmentation results of other categories. How can I modify the weight of the loss or the saving conditions of the model parameters?

**Comment by drprojects** [comment]
By default, our configs for semantic segmentation make the validation mIoU the main optimized metric. While other metrics can be computed and logged (e.g. mean IoU, per-class IoU, mean accuracy, overall accuracy, ...), the main optimized metric has a special role: is the one that is used for identifying the "best" model during training. If you want to make another metric the main metric, adjust the `optimized_metric` in your config file.

In your specific case, maybe you will need to also implement a new metric specific to the class you are interested in. Have a look at the existing code for `SemanticSegmentationModule`, we already compute per-class IoU, you should be able to get started from there.

If you have `weighted_loss: True` in your model config, the loss will indeed be class-weigthed. The specific weights are computed by `BaseDataset.get_class_weight()`. So if you need to make some adjustments, look into this specific function.

That being said, implementing these will be up to you. Indeed, due to the large amount of requests we receive, we cannot provide free individual support for user-specific implementations. We can only provide support for issues relative to the official code and datasets of we implemented ourselves.
