### ISSUE TITLE
About build my own dataset

### ISSUE THREAD

**Issue by yfq512** [drprojects/superpoint_transformer#181]
### ✅ Code of conduct checklist

- [X] 🌱 I am using the **_latest version_** of the [code](https://github.com/drprojects/superpoint_transformer/tree/master).
- [X] 📙 I **_thoroughly_** went through the [README](https://github.com/drprojects/superpoint_transformer/blob/master/README.md), but could not find the feature I need there.
- [X] 📘 I **_thoroughly_** went through the tutorial [slides](media/superpoint_transformer_tutorial.pdf), [notebook](notebooks/superpoint_transformer_tutorial.ipynb), and [video](https://www.youtube.com/watch?v=2qKhpQs9gJw), but could not find the feature I need there.
- [X] 📗 I **_thoroughly_** went through the [documentation](https://github.com/drprojects/superpoint_transformer/tree/master/docs), but could not find the feature I need there.
- [X] 📜 I went through the **_docstrings_** and **_comments_** in the [source code](https://github.com/drprojects/superpoint_transformer/tree/master) parts relevant to my problem, but could not find the feature I need there.
- [X] 👩‍🔧 I searched for [**_similar issues_**](https://github.com/drprojects/superpoint_transformer/issues), but could not find the feature I need there.
- [X] ⭐ Since I am showing interest in the project, I took the time to give the [repo](https://github.com/drprojects/superpoint_transformer/tree/master) a ⭐ to show support. **Please do, it means a lot to us !**

### 🚀 The feature, motivation and pitch

I have some point cloud data obtained by drones through images and 3D reconstruction (not collected by LiDAR), with a format of xyzrgb. I would like to train this data to segment buildings, vegetation, roads, etc. The scene is similar to the DALES dataset, but the data format is more similar to S3DIS. I plan to refer to S3DIS to build my own dataset. Do I need to modify some hyperparameters? I hope you can give me some suggestions. Thank you.

### 🔀 Alternatives

I tried [eclair-dataset](https://github.com/SharperShape/eclair-dataset), However, there are still some issues to be addressed.

**Comment by drprojects** [comment]
> The scene is similar to the DALES dataset, but the data format is more similar to S3DIS. I plan to refer to S3DIS to build my own dataset.

See the [datasets docs](docs/datasets.md) and the docstring of `BaseDataset` for how to create your own dataset class. Note that S3DIS has a very special raw file structure and, at preprocessing time, we aggregate all the S3DIS rooms into a single big cloud for each building area. DALES, on the other hand, has a more straightforward raw file structure, but its raw clouds are too large to be processed at once on, so we tile them at preprocessing time. These mechanisms may or may not be what you need, but be aware of them.

> Do I need to modify some hyperparameters? I hope you can give me some suggestions.

Unless you have the same classes, same sensor, and same resolution at one of our already-existing datasets, you will likely need to adjust some of the preprocessing parameters to suit your need. I have already provided many resources to help users do so on their own data. Please see the README, docs, notebooks, and the video tutorial I gave.

Due to the large number of requests I receive, I unfortunately do not have the bandwidth to provide free, individual support for implementing and parameterizing customized user datasets. I did strive, however, to provide very detailed notebooks, demo tutorial, and documented code to do so.

**Comment by yfq512** [comment]
@drprojects 
Thanks for your work.

I am experimenting with the Dales dataset on [notebooks/demo.ipynb](https://github.com/drprojects/superpoint_transformer/blob/master/notebooks/demo.ipynb), but I noticed that once the directory structure of the Dales dataset changes, DALESObjects.tar.gz gets re-extracted and overwrites the changes. It seems like a validation is performed on the dataset when running [hydra.utils.instantiate(cfg.datamodule)](https://github.com/drprojects/superpoint_transformer/blob/master/notebooks/demo.ipynb#L113). Is there a way to disable this validation strategy?

**Comment by drprojects** [comment]
Our code expects and maintains a specific file structure for each dataset. This lets us, among other things, keep track of different versions of preprocessing hyperparameters without overwriting. I will not provide support for circumventing this. If you need to, look at the `download()` and `process()` methods of your dataset class.
