### ISSUE TITLE
How to obtain the coordinates of a point of the full-resolution panoptic prediction?

### ISSUE THREAD

**Issue by 1163710216** [drprojects/superpoint_transformer#182]
![截图 2024-12-27 15-40-23](https://github.com/user-attachments/assets/bd56e39b-5cd7-4d21-ae6e-e006a8c8c878)

I am very confused about
how to obtain the coordinates of a point of the raw_obj_pred?

**Comment by yfq512** [comment]
nag shape and output shape is matched, If you look carefully, you will find that their index sequences are the same. You can verify this through some visualization methods.

**Comment by drprojects** [comment]
Please see #78.

We do not store the full-resolution point positions in the preprocessed files, so as to avoid duplicating the entire raw dataset on disk. The functions `full_res_seamantic_pred()` and `full_res_panoptic_pred()` are designed so as to return only the full-resolution **predictions** for points in the **same order as they are stored in the corresponding raw file**. For users who want to load the corresponding full-resolution point cloud position, color, or any other attribute their data may carry, we expect them to do so independently. This requires finding, for a given batch, which raw files have been used and which indexing/sampling was applied. To this end, I invite you to have a close look at how `BaseDataset.process()` operates, to understand how the raw clouds are processed with the `BaseDataset.pre_transform` and saved into the `processed/` directory.

I agree that a little helper function would be useful for easily recovering, from a loaded batch, the path to the corresponding raw file along with potential sampling due to `xy_tiling` or `pc_tiling`. Properly implementing for all datasets in an efficient manner requires a good understanding of our data processing and batching pipeline. This is not on our priority list at the moment, but we would gladly welcome a PR addressing this :wink:

PS: @1163710216 we have created github issue templates to help us monitor the issues we receive. Please use them next time
