### ISSUE TITLE
Implementing SensatUrban

### ISSUE THREAD

**Issue by JeppeVHolm** [drprojects/superpoint_transformer#35]
Hi Damian,

Thanks for SPT!
We are three university students trying to use SPT to classify point clouds.

We have been looking into incorporating the SensatUrban dataset into SPT. 
![Skærmbillede 2023-10-19 140859](https://github.com/drprojects/superpoint_transformer/assets/129040179/86749886-8bbc-4ccc-b807-87b8e616a8cc)
It seems as if the data read correctly, as shown in the picture above.

We tried looking into issue #15 to resolve it, but it did not work.
![Skærmbillede 2023-10-19 141249](https://github.com/drprojects/superpoint_transformer/assets/129040179/330db633-26d2-4cfe-bae6-5043283f239d)

Would you happen to have any suggestions on how to resolve this issue? We have been through the guide for setting up our own dataset several times and have found a lot of inspiration in how dales are setup. 

Looking forward to hearing from you.
Best regards Jeppe

**Comment by drprojects** [comment]
Hi, I am super happy someone is trying to integrate SensatUrban in the framework, I was hoping to do it at some point. I would gladly welcome a PR in the end once you have things working !

Normally, if you followed the existing code's style, you should only have to create the following:
- a `SensatUrbanDataModule` inheriting from `BaseDataModule` in `src/datamodules/sensaturban.py 
- a `SensatUrbanDataset` inheriting from `BaseDataset` in `src/datasets/sensaturban.py, along with its reader function to parse raw data files
- optional helper variables in `src/datasets/sensaturban_config.py`
- a datamodule config file `config/datamodules/sensaturban.yaml`

Is that what you have ? Have you made any other modifications to the project ? 

In particular, can you please share the code for:
- your datamodule  config file ?
- your raw data reading function ?

Since you checked #15 I am assuming you checked your semantic labels are dense in `[0, N[` and only use the `N` label for unclassified/unlabeled/ignored points ?

**Comment by cell1604** [comment]
Hi, another student from the same project group here.

Thank you so much for your response!

We didn't take our starting point in your base files as we are still newbies with regard to coding.
Instead, we copied each of the files you mentioned from Dales and adjusted these to Sensat.

Besides the files you are mentioning, we also added a line to src/datasets/_init_.py as you can see:

![image](https://github.com/drprojects/superpoint_transformer/assets/129041034/f5a8d452-7089-4a49-a46e-10aa48eb7990)

We have pushed our work at its current state to the following repository, where you can check our files:
https://github.com/cell1604/superpoint_transformer_P9/tree/spt_sensaturban

With regard to #15 : 
We went through all data files from SensatUrban to make sure they are annotated correctly. In this process we found some error in 3 files resulting that we couldn't open them, so we tried to remove these from the training data (didn't work). Furthermore we discovered that the data in "test" were not annotated and hence has no semantic labels (we assume that the test data should also have such?), so we also tried replacing the test data with data that were annotated - this didn't resolve the issue either.

As you may know, Sensat has 13 classes ranging from [0, 12], but does not have a class specifically for "Unknown" points - however, we have experimented forth and back trying to adding and removing a such class trying to figure out if it is a criteria in SPT? However we have not had any luck regardless of what we've tried. Maybe you can clarify how to configure this correctly?
 
![image](https://github.com/drprojects/superpoint_transformer/assets/129041034/3f1e456e-4047-4a94-8a00-bf2c4f0ba66e)

In #15, you suggested adding this line in data/data.py in order to check for empty tensors or something like that I figure?:

`assert a.sum(dim=1).gt(0).all(), f"Some points in the label histogram 'self.y' do not have any labels."`
However, we are not quite sure how to use this, as it seems to require "a" to be a defined tensor of some sort?

Looking forward hearing back from you!
Regards, Cellina

**Comment by drprojects** [comment]
Without further reply from you, I consider this issue solved and am closing it.

PS: if you are using and like the project, don't forget to all give us a ⭐, it matters to us !

**Comment by biophase** [comment]
Not sure if this helps anyone but I noticed the mentioned error also occurs if the conditions mentioned by @drprojects are met (e.g. labels in range [0,C]; all labels present at least once) **but** for some reason 1D labels are passed as a 2D array to the `Data` object with shape [N, 1], which is what you get if you e.g. read a ply file as pandas dataframe and pass a 'labels' column. I was able to fix this with `.reshape(-1)` on the labels.
