### ISSUE TITLE
Raw and Processed file

### ISSUE THREAD

**Issue by ywang864** [drprojects/superpoint_transformer#57]
![image](https://github.com/drprojects/superpoint_transformer/assets/111333965/0dfc3a85-e3ec-4312-9e4d-fe2e02ff3fef)
A quick question, where are these two data files come from?

**Comment by drprojects** [comment]
If you read the lines just below your screenshot on the documentation page:

### Automatic download and preprocessing
Following `torch_geometric`'s Dataset behavior:

Dataset instantiation
➡ Load preprocessed data in `data/<dataset_name>/processed`

Missing files in `data/<dataset_name>/processed` structure
➡ Automatic preprocessing using files in `data/<dataset_name>/raw`

Missing files in `data/<dataset_name>/raw` structure
➡ Automatic unzipping of the downloaded dataset in `data/<dataset_name>`

Missing downloaded dataset in `data/<dataset_name>` structure
➡ Automatic manual download to `data/<dataset_name>`


Said otherwise, you need to download the zip files as indicated, then the program will unzip what it needs in `raw/` and will save the preprocessed files in `processed/`.
