### ISSUE TITLE
Superpoint generation

### ISSUE THREAD

**Issue by jing-zhao9** [drprojects/superpoint_transformer#81]
Hello @drprojects,
Can the superpoint generation be replaced with a custom superpoint generation method, and then use your proposed superpoint_transformer for semantic segmentation?

**Comment by drprojects** [comment]
Yes, you can use another partition strategy. We are biased towards the formulation we peopose in the paper because it offers certain properties we judge desirable:
- no prior on the number of superpoints
- can be adapted to pretty much any pointwise features
- encourages superpoint contours with "simple" shapes
- does not produce non-connex superpoints

If you have another partition method, you can use it instead of our cut-pursuit formulation, as long as you express it in the expected format. For that you will need to get familiar with our data formats.

Howecer, note that one of the main contributions of our Superpoint Transformer paper is the design of a hierarchical superpoint partition. So your partition algorithm will also need to be hierarchical. See our ICCV'23 paper for more details.
