### ISSUE TITLE
there is no branch

### ISSUE THREAD

**Issue by gyy520cyaowu** [drprojects/superpoint_transformer#85]

**Comment by gyy520cyaowu** [comment]
hello, 
there is a question:
git clone -b improve_merge https://gitlab.com/1a7r0ch3/parallel-cut-pursuit.git src/dependencies/parallel_cut_pursuit
there is no branch named improve_merge, i go to this website and this package has only one branch that named 'master'

**Comment by drprojects** [comment]
The reliance on the `improve_merge` was only present in a past version of this repo. You are clearly using an old version of the code.

1. always update your code with the latest version _**before blindly filing an issue**_
2. several people got involved in promptly providing some help for addressing issues you already opened in this repo, answering those would be the _**minimum courtesy**_, so we know if the issue has been fixed

This is an open-source project, we are glad that people use it and get involved and let us know when they find bugs (eg #83 was totally legit and we thank you for pointing it out). But providing support is also time-consuming for us. So please be considerate of our time before opening an issue, make sure:
- you are using the latest version of the repo
- you have checked that the answer to your problem is not in already-existing issues
- your machine abides by the indicated hardware requirements
- you have followed our installation instructions
- your issue is related to the released code - we do not provide support for issues related to changes you may have made
