### ISSUE TITLE
    from cp_d0_dist import cp_d0_dist ModuleNotFoundError: No module named 'cp_d0_dist'

### ISSUE THREAD

**Issue by weilailoveL** [drprojects/superpoint_transformer#88]
When I configure the environment in windows system, this problem occurs, and there is no cp_d0_dist model in the code, how to solve it？

**Comment by drprojects** [comment]
Hi @weilailoveL you posted the same message in other unrelated issues.  Checking past issues in case your problem is already there is a good practice. Posting unrelated comments in existing issues in hope that you will get a faster answer is not. So I deleted your posts.

**Comment by drprojects** [comment]
As stated in the `README`, this project was build for linux machines. We do not support Window at the moment.

That being said, I can tell you where this error comes from, but will not provide further support for setting up the project on Windows.

This issue is related to the installation of the `parallel_cut_pursuit` dependency. When you run the `install.sh`, make sure the last compilation executed properly:

```bash
echo
echo
echo "⭐ Installing Parallel Cut-Pursuit"
echo
# Clone parallel-cut-pursuit and grid-graph repos
git clone https://gitlab.com/1a7r0ch3/parallel-cut-pursuit.git src/dependencies/parallel_cut_pursuit
git clone https://gitlab.com/1a7r0ch3/grid-graph.git src/dependencies/grid_graph

# Compile the projects
python scripts/setup_dependencies.py build_ext 
```

I cannot guarantee that this should compile at all on Windows and, as mentioned above and specified in the `README`, cannot provide support in case it does not because we only officially support Linux systems.
