### ISSUE TITLE
Inference on a single unlabeled .ply file

### ISSUE THREAD

**Issue by faridht** [drprojects/superpoint_transformer#93]
Hello! Thank you so much for this project!

I managed to go through the model retraining and evaluation (using the notebook demo). Presently however, I am trying to see the output of inference on a single unlabeled .ply file.

May you kindly advise on how this can be achieved? I tried to look into the docs and some issues, and it seems to me that the only way is through creating custom dataset files (Maybe I am misunderstanding or missing something).

Thank you very much in advance!

**Comment by drprojects** [comment]
Hello @faridht,

Normally you should be able to find what you need for running the inference on a cloud in [`notebooks/demo.ipynb`](https://github.com/drprojects/superpoint_transformer/blob/master/notebooks/demo.ipynb). This notebook shows how to run a forward pass on a `NAG` and visualize it with our tool.

Yet, since preparing a `NAG` for inference requires some preprocessing, you indeed should implement dedicated classes inheriting from `BaseDataset` and `BaseDatamodule` for your new data. If you have only one cloud tile in your dataset, this may sound overkill, but this is the cleanest, foolproof way of accessing all the features of this codebase. 

Then, you would want to use the [`predict()`](https://github.com/drprojects/superpoint_transformer?tab=readme-ov-file#pytorch-lightning-predict) logic.

A workaround would be that you manually instantiate and run the series of `Transform` for processing your raw data into a proper `NAG` for inference, and then run a forward pass on the model. These would be the ones you would otherwise find in your dataset's config file:
- `pre_transform`
- `val_transform`
- `on_device_val_transform`
-
If you are familiar enough with the project and `hydra` in particular, you definitely can try this strategy ! However, I will not dedicate much time further helping with this approach, since we do not officially support it and I foresee doing so would open the door to a whole world of new issues :sweat_smile:

**Comment by yfq512** [comment]
@faridht I encountered the same problem about inference on a single unlabeled .ply file, have you solved it? Can you provide a related demo? Thanks!

**Comment by faridht** [comment]
@yfq512 Unfortunately I haven't resolved this because of project time constraints, so I ended up with a different technical direction for the problem I was trying to solve.

**Comment by yfq512** [comment]
@faridht Thanks for your reply. I have been looking for a useful open-source project about 3D point cloud instance segmentation. Do you have any recommendations?
